### ISSUE TITLE
I Search er der ikke filename til ikon

### ISSUE THREAD

**Issue by TCAA-Web** [Webudvikler-TechCollege/trashguide_api#4]
Hvis man kalder search får man ikke ikonet med ud. 
Ved at tilføje "filename", til arrSections i "Search" kaldet på backenden, kan man få ikonet for den tilhørende kategori med ud. 
Eks. ved at søge på papir får man både titlen, ID og filename så man kan vise resultatet.

**Comment by Webudvikler-TechCollege** [comment]
Done :)
